version: '3'
services:
  client:
    image: 
    build:
      dockerfile: Dockerfile
      context: .
    command: yarn
    # User is needed here, as assets end up on the host system.
    user: ${CURRENT_UID}